Update best-practices.md
katalon-studio/katalon-studio pull request #558
Opened 2022-08-04 08:12 UTC by khabaonhi

2022-08-04 08:27 UTC, hohuyhoangg approved these changes

2022-08-08 01:54 UTC, Padoplin requested changes
You need to swap the whole content, not only the heading of Best Practices and News.

2022-08-08 05:57 UTC, khabaonhi commented
> You need to swap the whole content, not only the heading of Best Practices and News.



> You need to swap the whole content, not only the heading of Best Practices and News.

2022-08-08 05:59 UTC, khabaonhi commented
> You need to swap the whole content, not only the heading of Best Practices and News.

2022-08-09 08:50 UTC, Padoplin approved these changes

2022-08-09 08:50 UTC, merged