Update marketing-content.md
katalon-studio/katalon-studio pull request #663
Opened 2024-08-19 06:59 UTC by xuankimtran

2024-08-19 07:07 UTC, nhpthuy requested changes

2024-08-19 07:07 UTC, nhpthuy commented on katalon-start-page/marketing-content.md
> +[**Share your stories now**](https://forum.katalon.com/t/celebrate-our-newest-katalon-academy-milestones-win-30/141017?u=albert.vu)
Share your stories now!

2024-08-19 07:07 UTC, nhpthuy commented on katalon-start-page/marketing-content.md
> +[<img src="https://github.com/user-attachments/assets/40758ccd-f3b9-4ad1-a8c8-24511596cc03">](https://forum.katalon.com/t/celebrate-our-newest-katalon-academy-milestones-win-30/141017?u=albert.vu)
the image is kinda blurred, pls check em
![](https://files.slack.com/files-pri/T1X9F6G2Y-F07H8V6TWCW/screenshot_2024-08-19_at_2.04.38_pm.png)

2024-08-20 07:05 UTC, nhpthuy approved these changes

2024-08-20 07:22 UTC, thanhnle approved these changes

2024-08-20 07:23 UTC, merged