Official Release 10.0.0
katalon-studio/katalon-studio pull request #672
Opened 2024-10-29 07:14 UTC by nghiadhd-2702

2024-10-29 07:23 UTC, thvu-katalon requested changes

2024-10-29 07:23 UTC, thvu-katalon commented on free/latest_v10_release.json
> +        "location": "https://download.katalon.com/free/10.0.0/release/Katalon_Studio_Free_Windows_64-10.0.0.zip",
We removed `Free` in this edition. Please update all the names.

2024-10-29 07:26 UTC, nghiadhd-2702 commented
@thvu-katalon I fixed the comment

2024-10-29 09:21 UTC, thvu-katalon requested changes

2024-10-29 09:21 UTC, thvu-katalon commented on free/latest_v10_release.json
> +        "file": "mac_aarch64",
Please change this to `mac_arm64` for consistency with version 9. Same for other files.

2024-10-30 12:10 UTC, thvu-katalon approved these changes

2024-10-30 12:10 UTC, merged